name: generate-pdf-actions
on: [push]
jobs:
 concurrency-primer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      continue-on-error: true
    - name: install-texlive
      run: | 
        sudo apt-get install -q -y texlive-full texlive-latex-base
      shell: bash
    - uses: actions/setup-python@v5
      with:
          python-version: '3.10' 
    - name: install-pygments
      run: |
        python -m pip install --upgrade pip
        pip install pygments
    - name: make
      run: make
    - name: Create and Upload Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/v') 
      with:
        files: |
          ./concurrency-primer.pdf
